En este ejercicio, simularemos una imagen representada como un **array 3D** en NumPy. En procesamiento de imágenes, un array 3D suele representar una imagen con dimensiones `(altura, anchura, canales)`, donde los **canales** pueden ser **rojo (R), verde (G) y azul (B)** en imágenes a color.

### Tareas:

1. **Creación del array 3D**
    - Genera un array 3D de tamaño **4x4x3** con valores aleatorios entre **0 y 255** para simular una imagen en formato RGB.
    - Usa `np.random.randint()` para generar valores enteros.
2. **Indexación en el array 3D**
    - Extrae y muestra:
        - El primer píxel (posición `[0,0]`) con sus valores de color **(R, G, B)**.
        - El último píxel de la imagen (posición `[-1,-1]`).
        - El valor del canal rojo del píxel en la segunda fila y tercera columna.
3. **Slicing en el array 3D**
    - Extrae y muestra:
        - Toda la primera fila de la imagen (es decir, todos los píxeles de la primera fila con sus valores RGB).
        - Solo los valores del canal azul para todos los píxeles de la imagen.
        - Un recorte central de la imagen, seleccionando las filas y columnas intermedias (por ejemplo, de la posición `[1:3, 1:3, :]`).

In [6]:
import numpy as np
import random

imagen = np.random.randint(0, 256, (4, 4, 3))
print(imagen,"\n")

print("El primer pixel con sus valores R,G,B: \n",imagen[0, 0])
print("El ultimo pixel de la imagen: \n",imagen[-1, -1])
print("El valor del canal rojo en el pixel de la seg fila y terc columna: \n",imagen[1,2,0])


print("La primera fila de la imagen: \n",imagen[0])
print("Los valores del canal azul para todos los pixeles de la imagen: \n" , imagen[:,:,2])
print("Las filas y columnas intermedias de la imagen: \n",imagen[1:3, 1:3, :])

[[[206  29 103]
  [ 20 100 206]
  [ 64  43 193]
  [124  84  84]]

 [[  7 236 147]
  [173  80 190]
  [223 156 112]
  [194 203  25]]

 [[195 138 112]
  [170  21 199]
  [157  22 239]
  [  4  11  28]]

 [[ 98 250  26]
  [211 136 122]
  [188  64 119]
  [109 188 176]]] 

El primer pixel con sus valores R,G,B: 
 [206  29 103]
El ultimo pixel de la imagen: 
 [109 188 176]
El valor del canal rojo en el pixel de la seg fila y terc columna: 
 223
La primera fila de la imagen: 
 [[206  29 103]
 [ 20 100 206]
 [ 64  43 193]
 [124  84  84]]
Los valores del canal azul para todos los pixeles de la imagen: 
 [[103 206 193  84]
 [147 190 112  25]
 [112 199 239  28]
 [ 26 122 119 176]]
Las filas y columnas intermedias de la imagen: 
 [[[173  80 190]
  [223 156 112]]

 [[170  21 199]
  [157  22 239]]]
