In [2]:
'''**Objetivo:** Utilizar arrays en `NumPy` para gestionar y analizar un sistema de inventario de una tienda. Practicarás la creación de arrays de diferentes dimensiones y tipos, y manipularás datos relacionados con los productos de una tienda.

**Escenario:** Imagina que eres el encargado de gestionar el inventario de una tienda de electrónica. La tienda tiene diferentes productos, y necesitas hacer un seguimiento de las cantidades disponibles, los precios y las categorías de productos. Utilizarás `NumPy` para organizar esta información.

'''
#Crear un array unidimensional con el nombre de los productos: Tienes una lista de 5 productos: "Smartphone", "Tablet", "Laptop", "Auriculares", "Teclado". Imprímelo.
import numpy as np

productos = np.array(["Smartphone", "Tablet", "Laptop", "Auriculares","Teclado"])
print(productos)

#Crear un array bidimensional con la cantidad en stock de cada producto: La tienda tiene el siguiente stock de productos:
stock = np.array([["Smartphone", 50], 
                 ["Tablet", 30], 
                 ["Laptop", 15], 
                 ["Auriculares", 40],
                 ["Teclado", 60]])
print(stock)

#Crear un array tridimensional para registrar las ventas de cada producto durante una semana: Imagina que tienes un registro de ventas para cada uno de los 5 productos durante 3 días de la semana. Cada capa del array representará un día de ventas y las columnas serán las cantidades vendidas para cada producto:Día 1: [5, 3, 2, 6, 4]
#Día 2: [7, 4, 1, 8, 5]
#Día 3: [6, 2, 3, 5, 4]

ventas = np.array([[[5, 3, 2, 6, 4],
                    [7, 4, 1, 8, 5],
                    [6, 2, 3, 5, 4]]])
print("Estas son las ventas: \n",ventas)

#Crear un array de ceros para los productos no vendidos hoy: Los productos que no se han vendido hoy deben estar en cero. Crea un array de ceros para representar la cantidad de productos no vendidos de la tienda hoy. Imprime el array.
no_vendidos = np.zeros((1, 5))
print("Estos son los productos no vendidos: \n",no_vendidos)


#Crear un array de unos para los productos que están en promoción: Los productos en promoción tienen un valor de 1, mientras que los que no están en promoción tienen 0. Crea un array de unos y ceros, donde los productos en promoción tienen el valor 1. Los productos en promoción son el "Smartphone" y el "Teclado". Imprímelo.
promocion = np.ones((1,5))
promocion[0,1:4] = 0
print("Articulos en promocion: \n",promocion)

#Crear un array con un rango de precios de productos: La tienda tiene productos cuyo precio varía entre 50 y 1000 unidades monetarias. Crea un array con los precios de los productos, usando la función np.arange, y un paso de 50 unidades. Imprímelo.
precios = np.arange(50, 1001, 50)
print(precios)

#Crear un array de precios aleatorios: Crea un array con precios aleatorios para los productos entre 100 y 500 unidades monetarias, de tamaño 5. Imprímelo.
import random
precios_aleatorios = np.random.randint(100, 500, 5)
print(precios_aleatorios)

#Generar un array de números enteros aleatorios para la cantidad vendida: Utiliza np.random.randint para crear un array de 5 elementos, con valores aleatorios entre 1 y 10, que representen las unidades vendidas de cada producto hoy. Imprímelo.
cantidad_vendida = np.random.randint(1, 11, 5)
print(cantidad_vendida)


#Crear un array vacío para almacenar los valores de descuento: Crea un array vacío de tamaño 5x1 para almacenar los descuentos que se aplicarán a cada producto. Imprímelo.
descuentos = np.empty((5,1))
print(descuentos)

#Generar un array con valores espaciados para analizar el cambio en las ventas: Imagina que deseas analizar cómo cambian las ventas en diferentes intervalos de tiempo (por ejemplo, cada 2 horas). Utiliza np.linspacepara generar un array con 5 puntos de venta, distribuidos entre 0 y 1000 unidades, representando las ventas totales del día. Imprímelo.

'''ventas_totales = np.linspace(0, 1000, 5)
print(ventas_totales)'''


['Smartphone' 'Tablet' 'Laptop' 'Auriculares' 'Teclado']
[['Smartphone' '50']
 ['Tablet' '30']
 ['Laptop' '15']
 ['Auriculares' '40']
 ['Teclado' '60']]
Estas son las ventas: 
 [[[5 3 2 6 4]
  [7 4 1 8 5]
  [6 2 3 5 4]]]
Estos son los productos no vendidos: 
 [[0. 0. 0. 0. 0.]]
Articulos en promocion: 
 [[1. 0. 0. 0. 1.]]
[  50  100  150  200  250  300  350  400  450  500  550  600  650  700
  750  800  850  900  950 1000]
[117 468 113 392 438]
[ 5  4  2 10  2]
[[1.]
 [0.]
 [0.]
 [0.]
 [1.]]


'ventas_totales = np.linspace(0, 1000, 5)\nprint(ventas_totales)'