In [1]:
import numpy as np


# Crear un array de 25 elementos
array = np.arange(25)

# 2. Cambiar la forma del array a una matriz 5x5
matriz_5x5 = array.reshape(5, 5)
print("Matriz 5x5:")
print(matriz_5x5)

# 2. Cambiar la forma del array a una matriz 2x4
matriz_2x4 = array[:8].reshape(2, 4)
print("\nMatriz 2x4:")
print(matriz_2x4)

# 3. Aplanar el array a un vector
vector_aplanado = matriz_5x5.flatten()
print("\nArray aplanado (vector):")
print(vector_aplanado)

# 4. Transponer el array
matriz_transpuesta = matriz_5x5.T
print("\nMatriz 5x5 transpuesta:")
print(matriz_transpuesta)



Matriz 5x5:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

Matriz 2x4:
[[0 1 2 3]
 [4 5 6 7]]

Array aplanado (vector):
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]

Matriz 5x5 transpuesta:
[[ 0  5 10 15 20]
 [ 1  6 11 16 21]
 [ 2  7 12 17 22]
 [ 3  8 13 18 23]
 [ 4  9 14 19 24]]


In [ ]:
ejemplo1= np.array([3, 5, 6, 2])
ejemplo2= np.array([1, 4, 7, 8])

print("La suma entre arrays es: ", ejemplo1 + ejemplo2)  


#Crea dos arrays de matrices 2x2
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

# suma 
print("La suma entre arrays es: \n", array1 + array2)
# resta 
print("La resta entre arrays es: \n", array1 - array2)
# multiplicacion
print("La multiplicacion entre arrays es: \n", array1 * array2)
# division
print(f"La division entre arrays es: \n", array1 / array2)


#escalar 6
print("La multiplicacion del array1 por el escalar 6 es: \n", array1 * 6 )
print("La multiplicacion del array2 por el escalar 6 es: \n", array2 * 6 )


In [2]:
#SUMA ACUMULADA
import numpy as np

#Crea un vector con 25 elementos con valores aleatorios enteros y obten la suma
vector_aleatorio = np.random.randint(0, 30, 25)
print("El vector: ",vector_aleatorio)

suma_vector_aleatorio = np.cumsum(vector_aleatorio)
print("La suma acumulada del vector: ",suma_vector_aleatorio)

#Crea un vector con 25 elementos con valores aleatorios flotantes y obten la suma acumulada
vector_aleatorio = np.random.rand(25)
print("El vector:", vector_aleatorio)

suma_vector_flotante = np.cumsum(vector_aleatorio)
print("La suma acumulada del vector: ", suma_vector_flotante)



El vector:  [15  9 25  2  2 15 22 23  9 11 26 14 18 28  3  1  2  5 26  7  2 13  2 15
 23]
La suma acumulada del vector:  [ 15  24  49  51  53  68  90 113 122 133 159 173 191 219 222 223 225 230
 256 263 265 278 280 295 318]
El vector: [0.36100606 0.01276615 0.90218902 0.91522951 0.96827098 0.04410423
 0.28666727 0.80030089 0.86892208 0.49987316 0.37040995 0.40690666
 0.95162883 0.63743111 0.65798308 0.07089832 0.40732506 0.64938314
 0.51871721 0.29684163 0.58895143 0.06507333 0.32161159 0.35505854
 0.5974283 ]
La suma acumulada del vector:  [ 0.36100606  0.37377221  1.27596122  2.19119073  3.15946171  3.20356595
  3.49023322  4.2905341   5.15945618  5.65932934  6.02973929  6.43664596
  7.38827479  8.0257059   8.68368897  8.75458729  9.16191235  9.81129549
 10.3300127  10.62685432 11.21580575 11.28087908 11.60249067 11.95754921
 12.55497752]


In [2]:

import numpy as np
# En nuestra agencia se define cada casa como un vector con un formato [tamaño_m2, habitaciones, precio_miles_euros]
casa_1 = np.array([70, 2, 150])  # Casa 1
casa_2 = np.array([85, 3, 200])  # Casa 2
casa_3 = np.array([120, 4, 300]) # Casa 3
casa_4 = np.array([60, 2, 130])  # Casa 4

# Tenemos una nueva casa y queremos encontrar la casa más similar en el dataset
nueva_casa = np.array([80, 3, 190])

"""Imaginemos que cada casa es un punto en un espacio tridimensional, donde cada eje representa un atributo:
Eje X → Tamaño (m²)
Eje Y → Habitaciones
Eje Z → Precio (€)
Si graficamos estos puntos en un espacio 3D, la nueva casa estaría en algún lugar, y la distancia más corta a uno de los puntos existentes representaría la casa más similar."""

# Conjunto de casas representadas como vectores
casas = np.array([casa_1, casa_2, casa_3, casa_4])

# Función para calcular la distancia euclidiana entre dos vectores: d = raíz cuadrada ((x2 – x1)^2 + (y2 – y1)^2)
def distancia_euclidiana(v1, v2):
    return np.sqrt(np.sum((v1 - v2) ** 2)) # Usamos np.sum() para sumar todos los elemetos de un array.

# Calcular la distancia de la nueva casa a cada casa del dataset
distancias = [distancia_euclidiana(nueva_casa, casa) for casa in casas]

# Encontrar la casa más cercana
indice_casa_mas_parecida = np.argmin(distancias)  # Usamos np.argmin() para encontrar el vector más cercano en términos de distancia. Esta función devuelve el índice del menor valor en un array.
casa_mas_parecida = casas[indice_casa_mas_parecida]

print(f"La casa más similar a la nueva casa es: {casa_mas_parecida} con una distancia de {distancias[indice_casa_mas_parecida]:.2f}")

La casa más similar a la nueva casa es: [ 85   3 200] con una distancia de 11.18


In [3]:
g = np.array([1, 4, 9])

# Raíz cuadrada
h = np.sqrt(g)
print("Raíz cuadrada:", h)

# Exponente
i = np.exp(g)
print("Exponente:", i)

# Logaritmo
j = np.log(g)
print("Logaritmo:", j)

# Seno
k = np.sin(g)
print("Seno:", k)

# Coseno
l = np.cos(g)
print("Coseno:", l)

Raíz cuadrada: [1. 2. 3.]
Exponente: [2.71828183e+00 5.45981500e+01 8.10308393e+03]
Logaritmo: [0.         1.38629436 2.19722458]
Seno: [ 0.84147098 -0.7568025   0.41211849]
Coseno: [ 0.54030231 -0.65364362 -0.91113026]


In [4]:
import numpy as np

#supongamos que tenemos un conjunto de datos de discos de música con el siguiente formato: [número de canciones, premios grammy, ventas en miles de euros]. Cada disco es un vector en un espacio tridimensional. Dado un nuevo disco de nuestra discográfica queremos evaluar qué disco existente es más similar en términos de distancia euclidiana.

disco_1 = np.array([49, 4, 250])  # número_canciones, premios_grammy, ventas_miles_euros
disco_2 = np.array([60, 1, 212]) 
disco_3 = np.array([110, 2, 100]) 

nuevo_disco = np.array([80, 3, 190])

# vectores
discos = np.array([disco_1, disco_2, disco_3])

# distancia euclidiana entre dos vectores
def distancia(v1, v2):
    return np.sqrt(np.sum((v1 - v2) ** 2)) 

# Calcular distancia euclidiana
distancias = [distancia(nuevo_disco, discos) for disco in discos]

# Encontrar el disco mas parecido
indice_disco_mas_parecido = np.argmin(distancias)  # Usamos np.argmin() para encontrar el vector más cercano en términos de distancia. Esta función devuelve el índice del menor valor en un array.
disco_mas_parecido = discos[indice_disco_mas_parecido]

print(f"El disco más aparecido es : {disco_mas_parecido} con una distancia de {distancias[indice_disco_mas_parecido]:.2f}")

El disco más aparecido es : [ 49   4 250] con una distancia de 120.21


In [ ]:
!jupyter nbconvert --to pdf primer_viernes.ipynb