Eres un ingeniero de datos en un equipo de Fórmula 1 y debes analizar el rendimiento de **10 pilotos** en **5 carreras**. Para ello, trabajarás con matrices en NumPy para transformar los datos y extraer información útil.

### **Tareas:**

1. **Representar los datos** en un array bidimensional de NumPy donde cada fila sea un piloto y cada columna una carrera.
2. **Transformación de arrays:**
    - Reorganiza la matriz con `.reshape()` para analizar los datos de otra manera.
    - Usa `.ravel()` o `.flatten()` para convertir la matriz en un array 1D.
3. **Operaciones aritméticas:**
    - Calcula el promedio de posiciones por piloto y por carrera (`axis=0` y `axis=1`).
    - Aplica una penalización sumando un valor a cada posición y recalculando los valores.
4. **Producto escalar:**
    - Modela el rendimiento de dos pilotos como vectores y calcula su similitud mediante el **producto escalar**.
5. **Producto cruzado:**
    - Representa las posiciones de dos pilotos en las primeras tres carreras como vectores 3D y calcula su **producto cruzado**, interpretando el resultado en términos de diferencias de rendimiento.
6. **Extra bonus:**
    - Normaliza los datos usando la **norma L2** (`np.linalg.norm()`) para comparar el rendimiento de los pilotos en diferentes circuitos.

In [27]:
import numpy as np

pilotos = np.array ([
    [8, 7, 6, 9, 6],
    [6, 3, 5, 8, 8],
    [9, 8, 1, 7, 2],
    [7, 1, 7, 5, 4],
    [3, 4, 10, 1, 10],
    [2, 5, 2, 6, 9],
    [5, 10, 3, 4, 7],
    [1, 2, 4, 3, 5],
    [4, 9, 8, 10, 3],
    [10, 6, 9, 2, 1]
])

#.reshape()
pilotos_reshape = pilotos.reshape(5,10)
print(reshape)

#.ravel()
pilotos_1D = pilotos.ravel()
print(pilotos_1D)

#calcula el promedio de posiciones
promedio_pilotos = np.mean(pilotos, axis=1)
promedio_carreras = np.mean(pilotos, axis=0)
print(promedio_pilotos)
print(promedio_carreras)

#penalización 
pilotos_penalizados = pilotos + 3
print(pilotos_penalizados)

#producto escalar
piloto_1 = np.array([8, 7, 6, 9, 6])
piloto_2 = np.array([6, 3, 5, 8, 8])

producto_escalar = np.dot(piloto_1, piloto_2)
print("EL producto escalar de los primeros dos pilotos es: \n",producto_escalar)

#producto cruzado
piloto1_3d = piloto_1[:3]
piloto2_3d = piloto_2[:3]

producto_cruzado = np.cross(piloto1_3d, piloto2_3d)
print("El producto cruzado de los primeros dos pilotos es: \n", producto_cruzado)

#Normaliza los datos usando la norma L2 (np.linalg.norm()) para comparar el rendimiento de los pilotos en diferentes circuitos.
piloto_1_normalizado = piloto_1 / np.linalg.norm(piloto_1)
piloto_2_normalizado = piloto_2 / np.linalg.norm(piloto_2)
print("El piloto 1 normalizado es: \n", piloto_1_normalizado)
print("El piloto 2 normalizado es: \n", piloto_2_normalizado)



[[ 8  7  6  9  6  6  3  5  8  8]
 [ 9  8  1  7  2  7  1  7  5  4]
 [ 3  4 10  1 10  2  5  2  6  9]
 [ 5 10  3  4  7  1  2  4  3  5]
 [ 4  9  8 10  3 10  6  9  2  1]]
[ 8  7  6  9  6  6  3  5  8  8  9  8  1  7  2  7  1  7  5  4  3  4 10  1
 10  2  5  2  6  9  5 10  3  4  7  1  2  4  3  5  4  9  8 10  3 10  6  9
  2  1]
[7.2 6.  5.4 4.8 5.6 4.8 5.8 3.  6.8 5.6]
[5.5 5.5 5.5 5.5 5.5]
[[11 10  9 12  9]
 [ 9  6  8 11 11]
 [12 11  4 10  5]
 [10  4 10  8  7]
 [ 6  7 13  4 13]
 [ 5  8  5  9 12]
 [ 8 13  6  7 10]
 [ 4  5  7  6  8]
 [ 7 12 11 13  6]
 [13  9 12  5  4]]
EL producto escalar de los primeros dos pilotos es: 
 219
El producto cruzado de los primeros dos pilotos es: 
 [ 17  -4 -18]
El piloto 1 normalizado es: 
 [0.49051147 0.42919754 0.3678836  0.55182541 0.3678836 ]
El piloto 2 normalizado es: 
 [0.42640143 0.21320072 0.35533453 0.56853524 0.56853524]
