In [1]:
import numpy as np

jugador = np.array([
    [10, 7, 300, 25, 40],
    [15, 10, 250, 30, 50],
    [5, 12, 280, 20, 35],
    [8, 6, 310, 15, 38],
    [12, 9, 270, 28, 45]])

print(jugador,"\n")

norma_L2_jugadores = np.sum(jugador, axis=1, keepdims=True)
print("Esto es la L2: \n",norma_L2_jugadores)


normaL2_jugadores = np.sum(jugador, axis=0, keepdims=True)
print(normaL2_jugadores)

[[ 10   7 300  25  40]
 [ 15  10 250  30  50]
 [  5  12 280  20  35]
 [  8   6 310  15  38]
 [ 12   9 270  28  45]] 

Esto es la L2: 
 [[382]
 [355]
 [352]
 [377]
 [364]]
[[  50   44 1410  118  208]]
