In [7]:
import numpy as np

# Definimos dos vectores
vector_a = np.random.randint(1, 10, 3)
vector_b = np.random.randint(1, 10, 3)

print(vector_a)
print(vector_b)

# Calculamos el producto punto entre los dos vectores
producto_punto = np.dot(vector_a, vector_b)

print("Producto punto:", producto_punto)

''''''
vector_c = np.random.randint(1, 10, 3)
vector_d = np.random.randint(1, 10, 3)

print(vector_c)
print(vector_d)

producto_cruzado = np.cross(vector_c, vector_d)

print("Producto cruzado:", producto_cruzado)



[5 5 8]
[8 6 5]
Producto punto: 110
[9 5 9]
[3 9 2]
Producto cruzado: [-71   9  66]


In [26]:
import numpy as np


A = np.arange(5, 21, 5)
B = np.arange(100, 401, 100)
print(A)
print(B)

#L2 euclidiana
L2 = np.linalg.norm(B - A)
print(f"L2 entre A y B: {L2:.2f}")

#distancia desde el origen 
distancia_origenA = np.sqrt(np.sum(A ** 2))
distancia_origenB = np.sqrt(np.sum(B ** 2))

print(f"Distancia de origen de A: {distancia_origenA:.2f}")
print(f"Distancia de origen de B: {distancia_origenB:.2f}")

'''#L1 Manhattan
L1_A = np.linalg.norm(A, ord=1)
print("L1 de A",L1_A)

L1_B = np.linalg.norm(B, ord=1)
print("L1 de B",L1_B)'''

[ 5 10 15 20]
[100 200 300 400]
L2 entre A y B: 520.34
Distancia de origen de A: 27.39
Distancia de origen de B: 547.72
L1 de A 50.0
L1 de B 1000.0
